<a href="https://colab.research.google.com/github/Alecia113/NLP-Lab/blob/main/lab3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Neural Network Example**实战了有点
#identifying animal species (features)

In [4]:
import torch
import numpy as np

two features: two aspects 
1: animal have hair
2: animal have feathers
has hair [011000]
has feather [001001]
----input ^
0-Oher 1-Manmmal 2-Bird [012002]
---output/y ^

# aim: predict animal == bird/ manmmal/others

In [ ]:
'''
创建数据one-hot
Create our feature data
[hair,feather]:0: X; 1:✅
[1,0]: animal has hair + doesn't have feathers
'''

'''
转换数据；变张量
transform data --> torch data type (Pytorch)
【传说中的如何让老师进行测试】
# Uncomment the following line to print out if you want to see the details
# print(x_data_torch)
'''

'''
好像是将输出的数据也录入了数组。
0-other； 1-mammal 2-bird
#然后再转换成张量
'''

'''
记录数据特征，和输出类的数量;;;就是赋值
'''
#这个部分更像是准备数据
#print()

In [5]:
#perpare for data
x_data = np.array(
    [[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])  #创建数据one-hot

x_data_torch = torch.from_numpy(x_data).float() #转类型变张量，目前还是整数

y_data = np.array([0,1,2,0,0,2]) #output
y_data_torch = torch.from_numpy(y_data) #output torch

num_features = 2 # 2个特征--hair, feather
num_classes = 3 # 3 输出类 other,mammal,bird

**No hidden layer --- manual 🤚 parameter update (weight + bias)** EG


In [ ]:
'''
调包
nn
和矩阵准确率分数
'''
'''
initialize weight + bias manually🤚 + setup gredient
torch.randn returns --->tensor (random fill with) (from normal distribution with mean 0 + vaiance方差 1)
[standard normal distribution 标准正态分布]
  # 功能：从标准正态分布（均值为0，方差为1）中抽取的一组随机数。返回一个张量
sizes (int…) - 整数序列，定义输出张量的形状
out (Tensor, optinal) - 结果张量

该方法能够决定自动梯度机制是否需要为当前这个张量计算记录运算操作.
该方法能对当前张量的requires_grad属性进行原地操作.返回这个当前张量.

'''
# Learning Rate - determines the step size at each iteration while moving toward a minimum of a loss function

# Epoch - A measure of the number of times all of the training vectors are used once to update the weights.
#方法训练向量的次数。（训练向量来每次更新权重）
#尝试2000看会发生什么

'''
for 循环开始正向传播 forward propagation   calculation+ storage of intermediate variables(incl. outputs)
from input layer --> output layer 

'''

'''
softmax change each value--->(0,1) + all values  +  add up(sum) = 1
eg:  [8.04, 2.76, -6.52] -> [0.53 0.24 0.23]
(l唠割锐泽母 log_softmax )

#啊哈！算法；
#算法图解
先进行softmax 然后进行logarithm softmax 对数
softmax： exp(x_i) / exp(x).sum() and log_softmax: log(exp(x_i)) /exp(x).sum() ) #只是分子做log
log(softmax(x)) 但是实际做起来 is different + efficient
    # https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html#torch.nn.LogSoftmax
    def log_softmax(input: Tensor, dim: Optional[int]=None, _stacklevel: 
      int=3, dtype: Optional[int]=None) ->Tensor
'''

#然后损失 开始要对比情况了。计算消极log 可能损失;[计算负对数似然损失]
'''
torch.nn.functional.nll_loss(input, target, weight=None, 
size_average=None, ignore_index=-100, reduce=None, reduction='mean')

一般只赋值前两个张量就可以了
'''

'''
开始反向传播：back propagation 进行计算梯度。 优化WB 使用学习率 -学习率*W/B 的梯度数据  然后再清零
torch.no_grad()
https://blog.csdn.net/weixin_46559271/article/details/105658654?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522161629843016780357253890%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=161629843016780357253890&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_click~default-1-105658654.first_rank_v2_pc_rank_v29&utm_term=torch.no_grad
当你做反向传播时，不要累积梯度。
'''

'''

argmax函数：torch.argmax(input, dim=None, keepdim=False)返回指定维度最大值的序号，dim给定的定义是：the demention to reduce.也就是把dim这个维度的，变成这个维度的最大值的index。

https://blog.csdn.net/weixin_42494287/article/details/92797061?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522161630304416780269870820%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=161630304416780269870820&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-1-92797061.first_rank_v2_pc_rank_v29&utm_term=torch.argmax做什么用的


In [65]:
import torch.nn.functional as F
from sklearn.metrics import accuracy_score

W1 = torch.randn(num_features, num_classes, requires_grad=True)#torch.randn(2,3)
B1 = torch.randn(num_classes, requires_grad=True) #3

learning_rate = 0.01 

number_of_epochs = 2000

for epoch in range(number_of_epochs):

  z =torch.add(torch.matmul(x_data_torch, W1),B1) # 输入两个单词张量，和weight 和bias、 forward propagation；【其实感觉还是在整合数据】
  
  log_softmax = F.log_softmax(z,dim=1)  #nn.functional.log_softmax   【softmax--log】

  loss = F.nll_loss(log_softmax, y_data_torch)  # input target  ----loss【一个对数概率向量和一个目标标签】

  loss.backward() #calculate gradient
  with torch.no_grad():   #进入with 调用torch.no_grad 返回一个grad对象 torch.no_grad() 是一个上下文管理器，被该语句 wrap 起来的部分将不会track 梯度。
      W1.data -= learning_rate*W1.grad.data   #gradient descent
      B1.data -= learning_rate*B1.grad.data
  W1.grad.data.zero_() #reset gradient
  B1.grad.data.zero_()

  if epoch % 200 == 199:
    with torch.no_grad():        #预测不需要梯度的
        pred_outputs = torch.add(torch.matmul(x_data_torch ,W1),B1)  #重新开始做乘法，回到了最开始的时候。
        predicted = torch.argmax(pred_outputs, 1)  #不是.outputs 是——
        train_acc = accuracy_score(predicted.numpy(), y_data)
        print('Epoch:%d, loss: %.4f, train_acc:%.3f' %(epoch + 1, loss.item() , train_acc))

#result
print('Predicted :', predicted.numpy())
print('Truth :', y_data)
print('Accuracy : %.2f' %train_acc)


#训练准确度在增加，损失在降低
'''

Epoch:200, loss: 1.8851, train_acc:0.167
Epoch:400, loss: 1.1088, train_acc:0.833
Epoch:600, loss: 0.7822, train_acc:0.833
Epoch:800, loss: 0.6057, train_acc:1.000
Epoch:1000, loss: 0.4985, train_acc:1.000
Epoch:1200, loss: 0.4256, train_acc:1.000
Epoch:1400, loss: 0.3718, train_acc:1.000
Epoch:1600, loss: 0.3302, train_acc:1.000
Epoch:1800, loss: 0.2968, train_acc:1.000
Epoch:2000, loss: 0.2694, train_acc:1.000
Predicted : [0 1 2 0 0 2]
Truth : [0 1 2 0 0 2]
Accuracy : 1.00[suji]

有hidden

Epoch: 200, loss: 0.9641, train_acc: 0.500
Epoch: 400, loss: 0.8275, train_acc: 0.667
Epoch: 600, loss: 0.7101, train_acc: 0.833
Epoch: 800, loss: 0.6079, train_acc: 0.833
Epoch: 1000, loss: 0.5234, train_acc: 0.833
Epoch: 1200, loss: 0.4527, train_acc: 0.833
Epoch: 1400, loss: 0.3903, train_acc: 0.833
Epoch: 1600, loss: 0.3342, train_acc: 1.000
Epoch: 1800, loss: 0.2883, train_acc: 1.000
Epoch: 2000, loss: 0.2466, train_acc: 1.000
Finished
Predicted ： [0 1 2 0 0 2]
Truth : [0 1 2 0 0 2]
Accuracy : 1.00[suiji]

'''

Epoch:200, loss: 1.8851, train_acc:0.167
Epoch:400, loss: 1.1088, train_acc:0.833
Epoch:600, loss: 0.7822, train_acc:0.833
Epoch:800, loss: 0.6057, train_acc:1.000
Epoch:1000, loss: 0.4985, train_acc:1.000
Epoch:1200, loss: 0.4256, train_acc:1.000
Epoch:1400, loss: 0.3718, train_acc:1.000
Epoch:1600, loss: 0.3302, train_acc:1.000
Epoch:1800, loss: 0.2968, train_acc:1.000
Epoch:2000, loss: 0.2694, train_acc:1.000
Predicted : [0 1 2 0 0 2]
Truth : [0 1 2 0 0 2]
Accuracy : 1.00


# 换了顺序： Hidden layer + manual parameter update  有H + 🤚

In [ ]:
'''
in hidden layer neurons numbers
定义隐藏层的神经元 

input features, output neurons(in hidden layer)(numbers)--W1

B1=== let Bias(hidden layer) output candidates numbers.  (neurons in hidden layer 5)

wout input （neurons numbers [hidden], output(classes))

'''
#定义神经元构建WB 从单词到隐藏层神经元。   b 让b输出日志数量（神经元）【这地方不理解】 
#w out 从中间到边上，输出大类。   Bout = 设置bias 为输出候选数。即3（类数）
#设置学习率 和 周期
'''
然后开始进行内部的。从添加。
F.relu 激活函数。然后进行激活函数
然后进行softmax log 然后 import torch.nn.functional as F
fit函数中采用损失函数F.nll_loss()
NLLLoss 的 输入 是一个对数概率向量和一个目标标签. 它不会为我们计算对数概率. 适合网络的最后一层是log_softmax
----^还在准备数据
'''
#激活函数准备输出的做分析的数据；；；对数softmax
#损失loss，   反向传播损失
#反向传播损失
#然后学习率训练数据，（调学习率） 每次处理完都要清除数据zero

In [17]:
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import accuracy_score

n_hidden_1 = 5 #隐藏层中的神经元

W1 = torch.randn(num_features, n_hidden_1, requires_grad=True) #输入特征，输出（隐藏侧神经元数量）
B1 = torch.randn(n_hidden_1, requires_grad=True) # 让隐藏层；偏移输出 候选日期的数量。即5 隐藏层中的神经元数量
# w1 （ ……num_features， num_classes， requ）
#Bout = 没隐藏的b
Wout = torch.rand(n_hidden_1, num_classes, requires_grad=True)#输入神经元数，输出类

Bout = torch.randn(num_classes, requires_grad=True)  #输出类3

learning_rate=0.01 #没变
no_of_epochs = 2000 # nob

for epoch in range(no_of_epochs):
  z1 = torch.add(torch.matmul(x_data_torch, W1), B1) # no 变
  Zout = torch.add(torch.matmul(F.relu(z1), Wout), Bout) #  激活函数的加和

  log_softmax = F.log_softmax(Zout,dim=1) #no大变
  loss = F.nll_loss(log_softmax, y_data_torch) #no大变

  loss.backward()#nb
  with torch.no_grad():#nb
    W1.data -= learning_rate*W1.grad.data#nb
    B1.data -= learning_rate*B1.grad.data#nb
    
    Wout.data -= learning_rate*Wout.grad.data  #bian
    Bout.data -= learning_rate*Bout.grad.data  #b

  W1.grad.data.zero_()#nb
  B1.grad.data.zero_()#nb
  Wout.grad.data.zero_()#b
  Bout.grad.data.zero_()#b


  if epoch % 200 == 199:#nd
    with torch.no_grad():#nd
      z1 = torch.add(torch.matmul(x_data_torch ,W1),B1) #nd
      Zout = torch.add(torch.matmul(F.relu(z1),Wout),Bout)#d
      predicted = torch.argmax(Zout,1)#lued
      train_acc = accuracy_score(predicted.numpy(),y_data)#nd
      print('Epoch: %d, loss: %.4f, train_acc: %.3f' %(epoch +1, loss.item() , train_acc))
#nd
print("Finished") #分隔

#result
print('Predicted ：', predicted.numpy()) #Predicted ： [0 1 2 0 0 2]
print('Truth :', y_data)#Trure ： [0 1 2 0 0 2]
print('Accuracy : %.2f' %train_acc) #Accuracy :









Epoch: 200, loss: 0.9641, train_acc: 0.500
Epoch: 400, loss: 0.8275, train_acc: 0.667
Epoch: 600, loss: 0.7101, train_acc: 0.833
Epoch: 800, loss: 0.6079, train_acc: 0.833
Epoch: 1000, loss: 0.5234, train_acc: 0.833
Epoch: 1200, loss: 0.4527, train_acc: 0.833
Epoch: 1400, loss: 0.3903, train_acc: 0.833
Epoch: 1600, loss: 0.3342, train_acc: 1.000
Epoch: 1800, loss: 0.2883, train_acc: 1.000
Epoch: 2000, loss: 0.2466, train_acc: 1.000
Finished
Predicted ： [0 1 2 0 0 2]
Truth : [0 1 2 0 0 2]
Accuracy : 1.00


#**TEST**

In [25]:
#2.4
Bout.data -= learning_rate*Bout.grad.data  #b
print(Bout.data)

tensor([-1.9189, -0.1212,  0.2067])


In [24]:
#2.3
Zout = torch.add(torch.matmul(F.relu(z1), Wout), Bout) 
print(Zout)

tensor([[-0.5934,  0.7461,  1.3760],
        [-1.4566, -0.0133,  0.5646],
        [-1.8992,  0.0396,  0.2620],
        [-0.5934,  0.7461,  1.3760],
        [-0.5934,  0.7461,  1.3760],
        [-1.8286,  0.6143,  0.4600]], grad_fn=<AddBackward0>)


In [22]:
#2.2
Wout = torch.rand(n_hidden_1, num_classes, requires_grad=True)
print(Wout)

tensor([[0.7730, 0.1804, 0.5983],
        [0.9212, 0.4871, 0.7432],
        [0.5285, 0.3293, 0.5707],
        [0.7976, 0.9384, 0.7502],
        [0.0467, 0.3825, 0.1316]], requires_grad=True)


In [21]:
#2.1
Zout = torch.add(torch.matmul(F.relu(z1),Wout),Bout)
print(Zout)

tensor([[ 3.5850, -0.1930,  0.2251],
        [-0.6030,  0.0824, -0.4356],
        [-1.3784, -0.2961,  0.7000],
        [ 3.5850, -0.1930,  0.2251],
        [ 3.5850, -0.1930,  0.2251],
        [ 0.5547, -0.9210,  2.4629]], grad_fn=<AddBackward0>)


没隐藏层手动调参。 测试如下。


In [53]:
#16
tain_acc = accuracy_score(predicted.numpy(), y_data)
print(tain_acc)

1.0


In [52]:
#15
predicted = torch.argmax(pred_outputs, 1)
print(predicted)

tensor([0, 1, 2, 0, 0, 2])


In [48]:
#14
print(pred_outputs)

tensor([[ 1.3947,  0.6585,  0.5634],
        [ 0.9237, -0.4688,  0.6831],
        [-1.6573,  1.1094,  1.3526],
        [ 1.3947,  0.6585,  0.5634],
        [ 1.3947,  0.6585,  0.5634],
        [-1.1862,  2.2367,  1.2329]])


In [40]:
#13
B1.data -= learning_rate*B1.grad.data
print(B1.data)
#tensor([ 2.1613,  0.7510, -0.7514],  #tensor([ 34.8541,  -0.3064, -33.4468])

tensor([ 34.8541,  -0.3064, -33.4468])


In [38]:
#12
W1.data -= learning_rate*W1.grad.data
print(W1.data)


'''
tensor([[ 0.9477,  1.5061, -0.7059],
        [-0.3978, -0.5679, -0.0613]
        tensor([[ 0.3480,  0.0354,  0.5222],
        [ 2.0451, -0.0493,  1.2841]])
        '''

tensor([[ 0.3480,  0.0354,  0.5222],
        [ 2.0451, -0.0493,  1.2841]])


In [33]:
#11
loss = F.nll_loss(log_softmax, y_data_torch)
print(loss)

tensor(1.6704, grad_fn=<NllLossBackward>)


In [32]:
#10
log_softmax = F.log_softmax(z,dim=1)
print(log_softmax)

#https://blog.csdn.net/hao5335156/article/details/80607732?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522161629884116780265451148%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=161629884116780265451148&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-80607732.first_rank_v2_pc_rank_v29&utm_term=F.log_softmax
#加快计算速度，数值上也更稳定。


tensor([[-0.2611, -1.6715, -3.1738],
        [-0.2168, -1.9441, -2.9598],
        [-0.0504, -3.8751, -3.5608],
        [-0.2611, -1.6715, -3.1738],
        [-0.2611, -1.6715, -3.1738],
        [-0.0537, -3.5615, -3.7339]], grad_fn=<LogSoftmaxBackward>)


In [30]:
#9 torch.matmul 可以输入高维的；二维就是图通乘法
#输入多维就是把拖出来的一位作为batch 提出来。其他部分做矩阵乘法
#将b的第0维 5 broadcast 提出来。后两维做矩阵乘法
import pprint
a = torch.ones(3,4)
b = torch.ones(5,4,2)
c = torch.matmul(a,b)
print(c.shape)
pprint.pprint(c)
#https://blog.csdn.net/qsmx666/article/details/105783610?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522161629814016780271553753%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=161629814016780271553753&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-4-105783610.first_rank_v2_pc_rank_v29&utm_term=torch.matmul参数怎么用


torch.Size([5, 3, 2])
tensor([[[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]]])


In [26]:
#8
z =torch.add(torch.matmul(x_data_torch, W1),B1) #参数传递到 torch.add 后返回输入参数的求和结果作为输出
#torch.matmul 是常用乘法
print(z)

tensor([[ 2.1613,  0.7510, -0.7514],
        [ 2.5123,  0.7850, -0.2307],
        [ 4.5605,  0.7358,  1.0501],
        [ 2.1613,  0.7510, -0.7514],
        [ 2.1613,  0.7510, -0.7514],
        [ 4.2096,  0.7018,  0.5294]], grad_fn=<AddBackward0>)


In [24]:
#7
B1 = torch.randn(num_classes, requires_grad=True)
print(B1)

tensor([ 2.1613,  0.7510, -0.7514], requires_grad=True)


In [20]:
W1 = torch.randn(num_features, num_classes, requires_grad=True)
print(W1)

tensor([[ 0.9477,  1.5061, -0.7059],
        [-0.3978, -0.5679, -0.0613]], requires_grad=True)


In [14]:
#5
num_features = 2 # 2个特征--hair, feather
num_classes = 3 # 3 输出类 other,mammal,bird
print(num_features,num_classes)

2 3


In [12]:
#4
y_data_torch = torch.from_numpy(y_data)
print(y_data_torch)

tensor([0, 1, 2, 0, 0, 2])


In [10]:
#3
y_data = np.array([0,1,2,0,0,2])
print(y_data)

[0 1 2 0 0 2]


In [7]:
#2
x_data_torch = torch.from_numpy(x_data)
print(x_data_torch)
x_data_torch = torch.from_numpy(x_data).float()
print(x_data_torch)

tensor([[0, 0],
        [1, 0],
        [1, 1],
        [0, 0],
        [0, 0],
        [0, 1]])
tensor([[0., 0.],
        [1., 0.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 1.]])


In [3]:
#1
x_data = np.array(
    [[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
print(x_data)#竖着全打出来了 也就是一行为【】然后整个【】再（）放在数组当中

[[0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]]
